#!/usr/bin/env python3
"""Generate the occupancy map this package ships with.

The map is produced by this script rather than captured from a robot, so it is
reproducible and its geometry is documented rather than opaque. Writes a P5
(binary) PGM plus the matching map_server YAML.

The layout is deliberately ASYMMETRIC. A symmetric floorplan makes global
localization ambiguous -- the filter latches onto a mirrored pose and, once
resampling has removed the alternatives, cannot recover. Three rooms of
distinctly different proportions, an off-centre pillar and a single alcove give
the likelihood field enough structure to disambiguate.

Pixel convention (map_server): 254 = free, 0 = occupied, 205 = unknown. The
image's first row is the map's HIGHEST y, so the array is flipped on write.

Usage:
    python tools/make_map.py                 # write map/map.pgm + map.yaml
    python tools/make_map.py --show          # also print an ASCII preview
"""

import argparse
import os
from collections import deque

import numpy as np

FREE, OCCUPIED, UNKNOWN = 254, 0, 205

# Cell geometry. Coordinates are (x, y) with y = 0 at the BOTTOM; the write
# step flips to PGM row order. Rooms tile without overlapping.
WIDTH, HEIGHT, WALL = 240, 200, 3

ROOMS = [
    # (x0, y0, x1, y1, label)
    (0, 0, 110, 130, "A: large lower-left, 5.5 x 6.5 m"),
    (110, 70, 175, 200, "B: tall upper-middle, 3.25 x 6.5 m"),
    (110, 0, 240, 70, "C: wide lower-right, 6.5 x 3.5 m"),
    (20, 127, 52, 160, "D: alcove off room A"),
]

# Doorways, carved through the shared walls after the rooms are laid down.
DOORS = [
    (107, 95, 113, 118, "A <-> B through the x = 110 wall"),
    (125, 67, 148, 73, "B <-> C through the y = 70 wall"),
    (30, 124, 44, 133, "A <-> D alcove mouth"),
]

# Freestanding obstacles, placed off-centre to break left/right symmetry.
PILLARS = [
    (26, 30, 42, 46, "pillar in room A"),
    (196, 40, 206, 50, "pillar in room C"),
]


def build():
    """Returns a (height, width) uint8 array indexed [y][x], y = 0 at bottom."""
    # Everything starts unknown, so the exterior stays unknown rather than
    # pretending to be free space the robot could occupy.
    grid = np.full((HEIGHT, WIDTH), UNKNOWN, dtype=np.uint8)

    for x0, y0, x1, y1, _ in ROOMS:
        grid[y0:y1, x0:x1] = OCCUPIED
        grid[y0 + WALL:y1 - WALL, x0 + WALL:x1 - WALL] = FREE

    for x0, y0, x1, y1, _ in DOORS:
        grid[y0:y1, x0:x1] = FREE

    for x0, y0, x1, y1, _ in PILLARS:
        grid[y0:y1, x0:x1] = OCCUPIED

    return grid


def connected_components(grid):
    """Sizes of the 4-connected free-space components, largest first."""
    free = grid == FREE
    seen = np.zeros_like(free, dtype=bool)
    sizes = []
    for sy in range(HEIGHT):
        for sx in range(WIDTH):
            if not free[sy, sx] or seen[sy, sx]:
                continue
            size = 0
            q = deque([(sx, sy)])
            seen[sy, sx] = True
            while q:
                x, y = q.popleft()
                size += 1
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < WIDTH and 0 <= ny < HEIGHT \
                            and free[ny, nx] and not seen[ny, nx]:
                        seen[ny, nx] = True
                        q.append((nx, ny))
            sizes.append(size)
    return sorted(sizes, reverse=True)


def write_pgm(path, grid):
    image = np.flipud(grid)  # PGM row 0 is the highest y
    with open(path, "wb") as f:
        f.write(b"P5\n")
        f.write(b"# generated by tools/make_map.py\n")
        f.write(f"{WIDTH} {HEIGHT}\n255\n".encode("ascii"))
        f.write(image.tobytes())


def write_yaml(path, resolution):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Generated by tools/make_map.py -- do not hand-edit.\n")
        f.write("image: map.pgm\n")
        f.write(f"resolution: {resolution:.6f}\n")
        f.write("origin: [0.0, 0.0, 0.0]\n")
        f.write("negate: 0\n")
        f.write("occupied_thresh: 0.65\n")
        f.write("free_thresh: 0.196\n")


def show(grid, step=4):
    print("ASCII preview, top row = highest y.  '.' free  '#' wall  ' ' unknown")
    for y in range(HEIGHT - 1, -1, -step):
        row = "".join(
            "." if grid[y, x] == FREE else ("#" if grid[y, x] == OCCUPIED else " ")
            for x in range(0, WIDTH, step // 2 or 1)
        )
        print("  " + row)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default="map")
    parser.add_argument("--resolution", type=float, default=0.05,
                        help="metres per cell")
    parser.add_argument("--show", action="store_true", help="print an ASCII preview")
    args = parser.parse_args()

    grid = build()

    components = connected_components(grid)
    free = int((grid == FREE).sum())
    occupied = int((grid == OCCUPIED).sum())

    if args.show:
        show(grid)

    print(f"{WIDTH}x{HEIGHT} cells at {args.resolution} m/cell = "
          f"{WIDTH * args.resolution:.1f} x {HEIGHT * args.resolution:.1f} m")
    print(f"free {free}  occupied {occupied}  unknown {grid.size - free - occupied}")
    print(f"free area {free * args.resolution ** 2:.1f} m^2")
    print(f"free-space components: {components[:5]}")

    # A map whose free space is split into islands cannot be driven across, so
    # fail loudly rather than shipping it.
    if len(components) != 1:
        raise SystemExit(
            f"ERROR: free space has {len(components)} disconnected components "
            f"{components[:8]}; every room must be reachable.")

    os.makedirs(args.out_dir, exist_ok=True)
    write_pgm(os.path.join(args.out_dir, "map.pgm"), grid)
    write_yaml(os.path.join(args.out_dir, "map.yaml"), args.resolution)
    print(f"wrote {args.out_dir}/map.pgm and {args.out_dir}/map.yaml")


if __name__ == "__main__":
    main()
